# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_bpm}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2011-03-14}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/controllers/definitions_controller.rb",
    "app/controllers/processes_controller.rb",
    "app/controllers/rails_bpm_controller.rb",
    "app/controllers/sessions_controller.rb",
    "app/controllers/tasks_controller.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/tasks_helper.rb",
    "app/models/user.rb",
    "app/models/workitem.rb",
    "app/processes/my_process.rb",
    "app/views/definitions/index.haml",
    "app/views/definitions/show.haml",
    "app/views/forms/index.haml",
    "app/views/forms/show.haml",
    "app/views/layouts/application.haml",
    "app/views/layouts/tasks_base.haml",
    "app/views/processes/index.haml",
    "app/views/sessions/new.haml",
    "app/views/shared/_flash.haml",
    "app/views/tasks/_buttons.haml",
    "app/views/tasks/collect_data/show.haml",
    "app/views/tasks/index.haml",
    "app/views/tasks/show.haml",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/generators/USAGE",
    "lib/generators/rails_bpm/install_generator.rb",
    "lib/generators/rails_bpm_generator.rb",
    "lib/generators/templates/password",
    "lib/rack/ruote_admin_only.rb",
    "lib/rails_bpm.rb",
    "lib/rails_bpm/model.rb",
    "lib/rails_bpm/participant.rb",
    "lib/rails_bpm/process.rb",
    "lib/ruote_kit_init.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Route based BPM Engine for Rails 3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, ["= 1.2.3"])
      s.add_runtime_dependency(%q<sinatra>, ["= 1.0"])
      s.add_runtime_dependency(%q<sinatra-respond_to>, ["= 0.5.0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<ruote>, [">= 0"])
      s.add_runtime_dependency(%q<ruote-kit>, [">= 0"])
      s.add_runtime_dependency(%q<bcrypt-ruby>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<formtastic>, ["= 1.2.3"])
      s.add_dependency(%q<sinatra>, ["= 1.0"])
      s.add_dependency(%q<sinatra-respond_to>, ["= 0.5.0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<ruote>, [">= 0"])
      s.add_dependency(%q<ruote-kit>, [">= 0"])
      s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<formtastic>, ["= 1.2.3"])
    s.add_dependency(%q<sinatra>, ["= 1.0"])
    s.add_dependency(%q<sinatra-respond_to>, ["= 0.5.0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<ruote>, [">= 0"])
    s.add_dependency(%q<ruote-kit>, [">= 0"])
    s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
  end
end

